version: "3.8"
services:
  db:
    image: "postgres:13"
    working_dir: /usr/test
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12340
      - POSTGRES_DB=testtask
    networks:
      - testtask

  server:
    container_name: test
    build:
      context: ../Test_task
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - testtask

volumes:
  dbdata:

networks:
  testtask:
    driver: bridge
